[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents

Our application will have a front-end based in react and the data will be treated with Solid technology 

=== Technology decisions

* React: is a Javascript open source library designed for create user interfaces which we are going to realize the inferface from our application.
* Solid: is a proposed set of conventions and tools for building decentralized social applications based on Linked Data principles. Our application is based in this philosophy.
* Visual studio code: is a  code editor which we are going to use for development our application.


* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
